"""empty message

Revision ID: 5368526c0642
Revises: None
Create Date: 2015-10-30 17:09:38.939320

"""

# revision identifiers, used by Alembic.
revision = '5368526c0642'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('color', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'color')
    ### end Alembic commands ###
