"""empty message

Revision ID: 7c186ee0523
Revises: 34cc797034a8
Create Date: 2015-10-31 15:35:21.760703

"""

# revision identifiers, used by Alembic.
revision = '7c186ee0523'
down_revision = '34cc797034a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    ### end Alembic commands ###
